export const ROLES = {
  REQUESTER: 'REQUESTER',
  LECTURER: 'LECTURER',
  DEPARTMENT_COORDINATOR: 'DEPARTMENT_COORDINATOR',
  HOD: 'HOD',
  ASSOCIATE_DEAN: 'ASSOCIATE_DEAN',
  DEAN: 'DEAN',
  FINANCE_DIVISION: 'FINANCE_DIVISION',
  APPROVING_AUTHORITY: 'APPROVING_AUTHORITY',
  FINANCE_OFFICER: 'FINANCE_OFFICER',
  ADMIN: 'ADMIN'
} as const;

export const ROLE_VALUES = Object.values(ROLES);

export const ROLE_LABELS: Record<string, string> = {
  [ROLES.REQUESTER]: 'Requester / Staff Member',
  [ROLES.LECTURER]: 'Lecturer',
  [ROLES.DEPARTMENT_COORDINATOR]: 'Department Management Assistant / Department Coordinator',
  [ROLES.HOD]: 'Head of Department',
  [ROLES.ASSOCIATE_DEAN]: 'Associate Dean',
  [ROLES.DEAN]: 'Dean',
  [ROLES.FINANCE_DIVISION]: 'Financial Division',
  [ROLES.APPROVING_AUTHORITY]: 'Approving Authority',
  [ROLES.FINANCE_OFFICER]: 'Finance Officer',
  [ROLES.ADMIN]: 'Admin'
};

export const REQUEST_STATUSES = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_VERIFICATION: 'UNDER_VERIFICATION',
  UNDER_REVIEW: 'UNDER_REVIEW',
  INFO_REQUESTED: 'INFO_REQUESTED',
  REJECTED: 'REJECTED',
  APPROVED: 'APPROVED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
} as const;

export const REQUEST_STATUS_VALUES = Object.values(REQUEST_STATUSES);

export const REQUEST_STATUS_LABELS: Record<string, string> = {
  [REQUEST_STATUSES.DRAFT]: 'Draft',
  [REQUEST_STATUSES.SUBMITTED]: 'Submitted',
  [REQUEST_STATUSES.UNDER_VERIFICATION]: 'Under Verification',
  [REQUEST_STATUSES.UNDER_REVIEW]: 'Under Review',
  [REQUEST_STATUSES.INFO_REQUESTED]: 'Clarification Requested',
  [REQUEST_STATUSES.REJECTED]: 'Rejected',
  [REQUEST_STATUSES.APPROVED]: 'Approved',
  [REQUEST_STATUSES.PAYMENT_PENDING]: 'Pending Payment',
  [REQUEST_STATUSES.PAID]: 'Paid',
  [REQUEST_STATUSES.CANCELLED]: 'Cancelled'
};

export const STEP_STATUSES = {
  WAITING: 'WAITING',
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  INFO_REQUESTED: 'INFO_REQUESTED',
  REJECTED: 'REJECTED',
  SKIPPED: 'SKIPPED'
} as const;

export const STEP_TYPES = {
  VERIFICATION: 'VERIFICATION',
  APPROVAL: 'APPROVAL',
  FINANCE_REVIEW: 'FINANCE_REVIEW',
  PAYMENT: 'PAYMENT'
} as const;

export const STAFF_CATEGORIES = {
  ACADEMIC: 'ACADEMIC',
  NON_ACADEMIC: 'NON_ACADEMIC'
} as const;

export const ACCOUNT_REQUEST_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
} as const;

export const APPROVAL_ACTIONS = {
  APPROVE: 'APPROVE',
  VERIFY_FORWARD: 'VERIFY_FORWARD',
  REQUEST_INFO: 'REQUEST_INFO',
  REJECT: 'REJECT',
  RESPOND_CLARIFICATION: 'RESPOND_CLARIFICATION',
  MARK_PAID: 'MARK_PAID',
  RESUBMIT: 'RESUBMIT'
} as const;

export const REQUEST_TYPE_CODES = {
  LECTURE_HOURS: 'LECTURE_HOURS',
  PAPER_MARKING: 'PAPER_MARKING',
  EXAM_DUTIES: 'EXAM_DUTIES',
  TRAVEL_FUEL: 'TRAVEL_FUEL',
  GENERAL_REIMBURSEMENT: 'GENERAL_REIMBURSEMENT',
  SPECIAL_EQUIPMENT: 'SPECIAL_EQUIPMENT',
  RESEARCH_ACADEMIC: 'RESEARCH_ACADEMIC'
} as const;

export const SUBMITTER_ROLES = [ROLES.REQUESTER, ROLES.LECTURER];
export const APPROVER_ROLES = [
  ROLES.DEPARTMENT_COORDINATOR,
  ROLES.HOD,
  ROLES.ASSOCIATE_DEAN,
  ROLES.DEAN,
  ROLES.FINANCE_DIVISION,
  ROLES.APPROVING_AUTHORITY
];
export const FINANCE_ROLES = [ROLES.FINANCE_OFFICER];
export const ADMIN_ROLES = [ROLES.ADMIN];

export const DEFAULT_CURRENCY = 'LKR';
